  openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/auth/activate/{uidb64}/{token}/:
    get:
      operationId: api_auth_activate_retrieve
      parameters:
      - in: path
        name: token
        schema:
          type: string
        required: true
      - in: path
        name: uidb64
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          description: No response body
  /api/auth/me/:
    get:
      operationId: api_auth_me_retrieve
      tags:
      - api
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
          description: ''
    put:
      operationId: api_auth_me_update
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserInfo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserInfo'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
          description: ''
  /api/auth/password_reset/:
    post:
      operationId: api_auth_password_reset_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordReset'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PasswordReset'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PasswordReset'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordReset'
          description: ''
  /api/auth/password_reset_code/:
    post:
      operationId: api_auth_password_reset_code_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetCode'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PasswordResetCode'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PasswordResetCode'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordResetCode'
          description: ''
  /api/auth/refresh_from_cookie/:
    post:
      operationId: api_auth_refresh_from_cookie_create
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          description: No response body
  /api/auth/search/{search}/:
    get:
      operationId: api_auth_search_retrieve
      parameters:
      - in: path
        name: search
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPreView'
          description: ''
  /api/auth/send_activation/:
    post:
      operationId: api_auth_send_activation_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAuth'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserAuth'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserAuth'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAuth'
          description: ''
  /api/auth/signin/:
    post:
      operationId: api_auth_signin_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAuth'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserAuth'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserAuth'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAuth'
          description: ''
  /api/auth/signout/:
    post:
      operationId: api_auth_signout_create
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          description: No response body
  /api/auth/signup/:
    post:
      operationId: api_auth_signup_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRegister'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserRegister'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRegister'
          description: ''
  /api/auth/user/{username}/:
    get:
      operationId: api_auth_user_retrieve
      parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
          description: ''
  /api/auth/user/{username}/follow/:
    post:
      operationId: api_auth_user_follow_create
      parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
      tags:
      - api
      responses:
        '200':
          description: No response body
    delete:
      operationId: api_auth_user_follow_destroy
      parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
      tags:
      - api
      responses:
        '204':
          description: No response body
  /api/auth/user/{username}/followers/:
    get:
      operationId: api_auth_user_followers_retrieve
      parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPreView'
          description: ''
  /api/auth/user/{username}/following/:
    get:
      operationId: api_auth_user_following_retrieve
      parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPreView'
          description: ''
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    BlankEnum:
      enum:
      - ''
    GenderEnum:
      enum:
      - M
      - F
      type: string
      description: |-
        * `M` - Male
        * `F` - Female
    NullEnum:
      enum:
      - null
    PasswordReset:
      type: object
      properties:
        email:
          type: string
          format: email
        code:
          type: string
        new_password:
          type: string
        confirm_password:
          type: string
      required:
      - code
      - confirm_password
      - email
      - new_password
    PasswordResetCode:
      type: object
      properties:
        email:
          type: string
          format: email
      required:
      - email
    UserAuth:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          writeOnly: true
      required:
      - password
      - username
    UserInfo:
      type: object
      properties:
        username:
          type: string
          title: نام کاربری
          description: الزامی. 150 کاراکتر یا کمتر. فقط شامل حروف، اعداد، و علامات
            @/./+/-/_
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          readOnly: true
        password:
          type: string
          writeOnly: true
          title: گذرواژه
          maxLength: 128
        first_name:
          type: string
          title: نام
          maxLength: 150
        last_name:
          type: string
          title: نام خانوادگی
          maxLength: 150
        bio:
          type: string
          nullable: true
        gender:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/GenderEnum'
          - $ref: '#/components/schemas/BlankEnum'
          - $ref: '#/components/schemas/NullEnum'
        birthday:
          type: string
          format: date
          nullable: true
        avatar:
          type: string
          format: uri
          nullable: true
        followers:
          type: string
          readOnly: true
        following:
          type: string
          readOnly: true
      required:
      - email
      - followers
      - following
      - password
      - username
    UserPreView:
      type: object
      properties:
        username:
          type: string
          title: نام کاربری
          description: الزامی. 150 کاراکتر یا کمتر. فقط شامل حروف، اعداد، و علامات
            @/./+/-/_
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          title: نام
          maxLength: 150
        last_name:
          type: string
          title: نام خانوادگی
          maxLength: 150
        avatar:
          type: string
          format: uri
          nullable: true
        is_follow:
          type: string
          readOnly: true
      required:
      - is_follow
      - username
    UserRegister:
      type: object
      properties:
        pk:
          type: integer
          readOnly: true
          title: ID
        username:
          type: string
          title: نام کاربری
          description: الزامی. 150 کاراکتر یا کمتر. فقط شامل حروف، اعداد، و علامات
            @/./+/-/_
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
        password:
          type: string
          writeOnly: true
          title: گذرواژه
          maxLength: 128
      required:
      - email
      - password
      - pk
      - username
